name: machmate_controller
description: "A new Flutter project."
publish_to: "none"

version: 1.1.0+9

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.11.1
  shared_preferences: ^2.2.2
  fluttertoast: ^9.0.0
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  rename: ^3.1.0
  connectivity_plus: ^6.0.2
  wifi_iot: ^0.3.19
  http: ^1.2.0
  url_launcher: ^6.3.1
  receive_intent: ^0.2.4
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # <-- Added
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" # <-- Path to your icon

flutter_native_splash:
  android: true
  color: "#FFFFFF"
  image: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash_logo.png
